# generated by datamodel-codegen:
#   filename:  sprotty/diagramOpenInTextEditor.json
#   timestamp: 2025-04-17T11:51:34+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel

from ..lsp import range as range_1
from ..lsp.requestMessage import RequestMessage


class Method(Enum):
    diagram_openInTextEditor = 'diagram/openInTextEditor'


class Location(BaseModel):
    uri: str
    range: range_1.Range


class Params(BaseModel):
    location: Location
    forceOpen: bool


class DiagramOpenintexteditor(RequestMessage):
    method: Optional[Method] = 'diagram/openInTextEditor'
    params: Params
