# Generated by Django 4.2.13 on 2024-07-18 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("djangoldp_tamis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestationstep",
            name="prestation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="djangoldp_tamis.prestation",
            ),
        ),
    ]
