# Generated by Django 4.2.16 on 2024-10-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_tamis', '0012_commande_prestation_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de démarrage'),
        ),
    ]
