# generated by datamodel-codegen:
#   filename:  lsp/generalSendMessage.json
#   timestamp: 2025-04-17T11:51:34+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from .requestMessage import RequestMessage


class Method(Enum):
    general_sendMessage = 'general/sendMessage'


class GeneralSendmessage(RequestMessage):
    method: Optional[Method] = 'general/sendMessage'
    params: List[str]
