"""
我们保存接口获取的字段信息，用来比较是否有新增或者减少
"""
PERSONAL_CENTER_MY_DETAIL_FIELDS = {
    'user_id': '用户ID',
    'avatar': '头像',
    'certificateValidity': '_certificateValidity',
    'code': '_code',
    'companies': '_companies',  # json
    'companiesCp': '_companiesCp',
    'createUid': '用户创建ID',
    'ctime': '用户创建时间',
    'depts': 'depts',  # json
    'email': '邮箱',
    'enableStatus': '_enableStatus',
    'groupAlias': '_groupAlias',
    'groupName': '_groupName',
    'introduction': '_introduction',
    'lastCommitCertInfoTime': '_lastCommitCertInfoTime',
    'lastLoginTime': '_lastLoginTime',
    'name': '真实姓名',
    'orgCp': '_orgCp',  # json
    'orgId': '_orgId',
    'orgName': '所属部门',
    'orgVo': '_orgVo',  # json
    'passwordComplex': '_passwordComplex',
    'phone': '手机号码',
    'relName': '常用名',
    'roles': '用户角色',  # json
    'sex': '性别',
    'signature': '_signature',
    'sourceType': '_sourceType',
    'type': '_type',
    'updateUid': '更新用户ID',
    'updateUname': '更新用户名字',
    'username': '用户名',
    'utime': '用户更新时间',
    'wxNumber': '微信号'}

# 供应商结算单详情
SETTLEMENT_INFO_LIST_FIELDS = {
    'attachmentFiles': '附件文件',
    'cname': '创建者',
    'code': '供应商结算单ID',
    'contractCode': '内部合同编号Code',
    'contractId': '内部合同编号ID',
    'contractOfflineCode': '内部合同编号',
    'contractStatus': '内部合同编号状态',
    'cpDisplayName': '所属公司',
    'cpId': '所属公司ID',
    'cpName': '所属公司名字',
    'ctime': '创建时间',
    'endTime': '结束时间',
    'frozenStatus': '冻结状态',
    'id': '结算单ID',
    'isCanApprove': '可以审核',
    'liableManName': '负责人名字',
    'name': '名字',
    'ogTotleAmount': '原始分成总计',
    'settlementCurrency': '结算货币',
    'settlementCurrencyStr': '结算货币名字',
    'spDisplayName': '结算渠道',
    'spId': '结算渠道ID',
    'spName': '结算渠道',
    'startTime': '开始时间',
    'status': '当前状态',
    'statusStr': '当前状态名字',
    'supplierDisplayName': '供应商显示名称',
    'supplierId': '供应商名称ID',
    'supplierName': '供应商名称',
    'totleAmount': '实际分成总计',
    'uname': '操作用户',
    'utime': '操作时间',
    # 后面添加的
    'deDeposit': '_deDeposit',
    'deOtherAmount': '_deOtherAmount',
    'shareProportion': '_shareProportion',
    'exchangeRate': '_exchangeRate',
    'divideType': '_divideType',
    'divisionMethod': '_divisionMethod',
    # 20241101 添加的内容
    'divisionMethodNames': '合作模式',  # 内容是一个文本列表
    'shareProportions': '分成比例',  # 内容是一个百分比文本列表
    'shareBeginEndTimes': '分成起止时间',  # 内容是一个时间间隔的文本列表
    'copyrightTypeRecord': '_copyrightTypeRecord',
    'copyrightTypeLyric': '_copyrightTypeLyric',
    'copyrightTypeMusic': '_copyrightTypeMusic',
    'copyrightTypeMv': '_copyrightTypeMv',
    'minPayBalance': '_minPayBalance',
    'otherFeeBalance': '_otherFeeBalance',
    'shareBeginDate': '_shareBeginDate',
    'shareEndDate': '_shareEndDate',
    'divisionRuleId': '_divisionRuleId',
}

# 供应商结算单详情
SETTLEMENT_INFO_FIELDS = {
    'attachmentFiles': '附件文件',
    'cname': '创建者',
    'code': '供应商结算单号',
    'contractCode': '合同Code',
    'contractId': '合同ID',
    'contractOfflineCode': '内部合同编号',
    'contractStatus': '内部合同编号状态',
    'cpDisplayName': '所属公司显示名字',
    'cpId': '所属公司Id',
    'cpName': '所属公司名字',
    'ctime': '创建时间',
    'deDeposit': '扣减保底金',
    'deOtherAmount': '扣减其他费用',
    'divisionMethod': '合作模式Id',
    'endTime': '结算结束时间',
    'frozenStatus': '冻结状态',
    'id': '供应商结算单ID',
    'isCanApprove': '可以审核',
    'liableManName': '合约负责人',
    'name': '名字',
    'ogTotleAmount': '原始分成总计',
    'settlementCurrency': '结算货币ID',
    'settlementCurrencyStr': '结算货币名字',
    'shareProportion': '合同分成比例',
    'spDisplayName': '结算渠道显示名字',
    'spId': '结算渠道Id',
    'spName': '结算渠道名字',
    'startTime': '结算开始时间',
    'status': '当前状态ID',
    'statusStr': '当前状态名字',
    'supplierDisplayName': '供应商显示名字',
    'supplierId': '供应商ID',
    'supplierName': '供应商名字',
    'totleAmount': '实际分成合计',
    'uname': '更新用户',
    'utime': '更新时间',
    # 后面添加的
    'exchangeRate': '_exchangeRate',
    'divideType': '_divideType',
    'exchRateDetail': '_exchRateDetail',
    'currentSettInfo': '_currentSettInfo',
    'innerInfos': '_innerInfos',
    # 20241101 删除的内容
    # 'divisionMethodName': '合作模式',
    # 'relationSupplierDocCode': '_relationSupplierDocCode',
    # 'relationSupplierDocId': '_relationSupplierDocId',
    # 'settleFormula': '结算公式',
    # 20241101 添加的内容
    'minPayBalance': '_minPayBalance',
    'otherFeeBalance': '_otherFeeBalance',
    'divisionRuleId': '_divisionRuleId',
}

# 采购合约列表
CP_CONTRACT_LIST_FIELDS = {
    'attachmentFiles': '附件文件数据',  # 列表数据
    'attachmentType': '附件文件类型',  # 列表
    'authName': '他方签约主体全称',
    'authOrgDisplayName': '他方签约主体显示名称',
    'authOrgId': '他方签约主体',
    'authOrgName': '他方签约主体常用名',
    'authOrgType': '他方签约主体类型',
    'authScope': '_authScope',
    'brandCode': '所属厂牌CODE',
    'brandDisplayName': '所属厂牌显示名称',
    'brandId': '所属厂牌ID',
    'brandName': '所属厂牌全称',
    'cid': '创建者ID',
    'cname': '创建者',
    'code': '合约CODE',
    'companyId': '_companyId',
    'contactsAddress': 'CP联系人地址',
    'contactsEmail': 'CP联系人邮箱',
    'contactsName': 'CP指定联系人',
    'contactsPhone': 'CP联系人电话',
    'contractBeginDate': '合约生效时间',
    'contractEndDate': '合约截止时间',
    'contractProperty': '合约属性',
    'contractPutOffM': '_contractPutOffM',
    'contractPutOffY': '_contractPutOffY',
    'contractStopMode': '_contractStopMode',
    'ctime': '创建时间',
    'dataSourceType': '_dataSourceType',
    'demoCopyrightType': '_demoCopyrightType',  # 列表
    'effectiveRemark': '_effectiveRemark',
    'explain': '合约说明',
    'fileId': '文件ID',
    'id': '合约ID',  # 改为 cp_id
    'identification': '_identification',
    'isCanApprove': '可以审核',
    'liableManEmail': '负责人邮箱',
    'liableManId': '合约负责人ID',
    'liableManName': '合约负责人',
    'liableManPhone': '负责人电话',
    'listStatus': '_listStatus',
    'name': '合约名称',
    'offlineCode': '内部合约编号',
    'orgType': '_orgType',
    'originAuthName': '原始授权方全称',
    'originAuthOrgDisplayName': '原始授权方显示名称',
    'originAuthOrgId': '原始授权方ID',
    'originAuthOrgName': '原始授权方名称',
    'originAuthOrgType': '原始授权方类型',
    'otherAuthOrgs': '其他授权方数据',  # 列表数据
    'ourMainSignOrgId': '_ourMainSignOrgId',
    'ourSignOrgId': '我方签约主体ID',
    'ourSignOrgName': '我方签约主体',
    'outContractNo': '外部合约编号',
    'productActualCount': '实际歌曲数',
    'productCount': '合约歌曲数',
    'relationContractExplain': '_relationContractExplain',
    'relationContractNo': '_relationContractNo',
    'signTime': '合约签署时间',
    'status': '合约状态',
    'type': '资产类型',  # 列表
    'uid': '更新用户ID',
    'uname': '更新用户',
    'utime': '更新时间',
    # 20241101 添加的内容
    'ourSignName': '_ourSignName',
    'minPayBalance': '_minPayBalance',
    'otherFeeBalance': '_otherFeeBalance',
    'cpBeginEndTime': '_cpBeginEndTime',
    'divisionMethodNames': '合作模式',  # 内容是一个文本列表
    'shareProportions': '分成比例',  # 内容是一个文本列表
    'shareBeginEndTimes': '分成起止时间',  # 内容是一个文本列表
}

# 采购合约详情
CP_CONTRACT_FIELDS = {
    'attachmentFiles': '附件文件数据',  # 列表数据
    'attachmentType': '附件文件类型',  # 列表
    'authName': '他方签约主体全称',
    'authOrgDisplayName': '他方签约主体显示名称',
    'authOrgId': '他方签约主体',
    'authOrgName': '他方签约主体常用名',
    'authOrgType': '他方签约主体类型',
    'authScope': '_authScope',
    'brandCode': '所属厂牌CODE',
    'brandDisplayName': '所属厂牌显示名称',
    'brandId': '所属厂牌ID',
    'brandName': '所属厂牌全称',
    'cid': '创建者ID',
    'cname': '创建者',
    'code': '合约CODE',
    'companyId': '_companyId',
    'contactsAddress': 'CP联系人地址',
    'contactsEmail': 'CP联系人邮箱',
    'contactsName': 'CP指定联系人',
    'contactsPhone': 'CP联系人电话',
    'contractBeginDate': '合约生效时间',
    'contractEndDate': '合约截止时间',
    'contractProperty': '合约属性',
    'contractPutOffM': '_contractPutOffM',
    'contractPutOffY': '_contractPutOffY',
    'contractStopMode': '_contractStopMode',
    'ctime': '创建时间',
    'dataSourceType': '_dataSourceType',
    'demoCopyrightType': '_demoCopyrightType',  # 列表
    'effectiveRemark': '_effectiveRemark',
    'explain': '合约说明',
    'fileId': '文件ID',
    'id': '合约ID',  # 改为 cp_id
    'identification': '_identification',
    'isCanApprove': '可以审核',
    'liableManEmail': '负责人邮箱',
    'liableManId': '合约负责人ID',
    'liableManName': '合约负责人',
    'liableManPhone': '负责人电话',
    'listStatus': '_listStatus',
    'name': '合约名称',
    'offlineCode': '内部合约编号',
    'orgType': '_orgType',
    'originAuthName': '原始授权方全称',
    'originAuthOrgDisplayName': '原始授权方显示名称',
    'originAuthOrgId': '原始授权方ID',
    'originAuthOrgName': '原始授权方名称',
    'originAuthOrgType': '原始授权方类型',
    'otherAuthOrgs': '其他授权方数据',  # 列表数据
    'ourMainSignOrgId': '_ourMainSignOrgId',
    'ourSignOrgId': '我方签约主体ID',
    'ourSignOrgName': '我方签约主体',
    'outContractNo': '外部合约编号',
    'productActualCount': '实际歌曲数',
    'productCount': '合约歌曲数',
    'relationContractExplain': '_relationContractExplain',
    'relationContractNo': '_relationContractNo',
    'signTime': '合约签署时间',
    'status': '合约状态',
    'type': '资产类型',  # 列表
    'uid': '更新用户ID',
    'uname': '更新用户',
    'utime': '更新时间',
    # 20241101 添加的内容
    'ourSignName': '_ourSignName',
    'minPayBalance': '_minPayBalance',
    'otherFeeBalance': '_otherFeeBalance',
    'cpBeginEndTime': '_cpBeginEndTime',
    'divisionMethodNames': '合作模式',  # 内容是一个文本列表
    'shareProportions': '分成比例',  # 内容是一个文本列表
    'shareBeginEndTimes': '分成起止时间',  # 内容是一个文本列表
}

# 支付单列表
SETTLEMENT_PAYMENT_DOCUMENT_LIST_FIELDS = {
    'accountName': '收款方名字',
    'accountNum': '收款方银行账号',
    'bankName': '收款方开户行名字',
    'bfDeDepositBalance': '扣减前保底金余额',
    'bfDeOtherAmountBalance': '扣减前其他费用余额',
    'cname': '创建者',
    'code': '支付单CODE',
    'confirmInfo': '_confirmInfo',
    'confirmStatus': '_confirmStatus',
    'contractCode': '内部合同Code',
    'contractId': '内部合同ID',
    'contractName': '内部合同名称',
    'contractOfflineCode': '内部合同编号',
    'contractStatus': '内部合同编号状态',
    'cpDisplayName': '所属公司显示名字',
    'cpId': '所属公司Id',
    'cpName': '所属公司名字',
    'ctime': '创建时间',
    'deDeposit': '扣减保底金',
    'deOtherAmount': '扣减其他费用',
    'divisionMethodName': '合作模式',
    'endTime': '结算结束时间',
    'id': '支付单Id',
    'isCanApprove': '可以审核',
    'liableManName': '合约负责人',
    'name': '支付单名称',
    'ogTotleAmount': '原始分成总计',
    'payTotleAmount': '实际分成合计',
    'paymentAttachments': '支付单附件',  # 支付单附件 一个包含字典的列表
    'paymentInvoiceAttachments': '_paymentInvoiceAttachments',
    'paymentReceiptAttachments': '_paymentReceiptAttachments',
    'settleFormula': '结算公式',
    'settlementCurrency': '结算货币ID',
    'settlementCurrencyStr': '结算货币名字',
    'shareAchievedAmount': '_shareAchievedAmount',
    'shareProportion': '合同分成比例',
    'spDisplayName': '结算渠道显示名字',
    'spId': '结算渠道Id',
    'spName': '结算渠道名字',
    'startTime': '结算开始时间',
    'sid': '_sid',
    'sstatus': '_sstatus',
    'shareInterval': '_shareInterval',
    'status': '状态',
    'statusStr': '当前状态名字',
    'supplierDisplayName': '供应商显示名字',
    'supplierId': '供应商ID',
    'supplierName': '供应商名字',
    'totleAmount': '实际分成合计',
    'uname': '更新用户',
    'utime': '更新时间',
    # 20241101 删除的内容
    # 'divisionMethod': '合作模式Id',
    # 20241101 添加的内容
    'divisionRuleId': '_divisionRuleId',
    'divisionModeNames': '_divisionModeNames',  # 内容是一个文本列表
    'shareProportions': '分成比例',  # 内容是一个百分比文本列表
    'bname': '_bname',
    'fname': '_fname',
    'zname': '_zname',
    'copyrightTypeRecord': '_copyrightTypeRecord',
    'copyrightTypeLyric': '_copyrightTypeLyric',
    'copyrightTypeMusic': '_copyrightTypeMusic',
    'copyrightTypeMv': '_copyrightTypeMv',
    'minPayBalance': '_minPayBalance',
    'otherFeeBalance': '_otherFeeBalance',
    'settlePaymentProofGenerationStatus': '_settlePaymentProofGenerationStatus',
}

# 支付单详情
SETTLEMENT_PAYMENT_DOCUMENT_DETAIL_FIELDS = {
    'accountName': '收款方名字',
    'accountNum': '收款方银行账号',
    'bankName': '收款方开户行名字',
    'bfDeDepositBalance': '扣减前保底金余额',
    'bfDeOtherAmountBalance': '扣减前其他费用余额',
    'cname': '创建者',
    'code': '支付单CODE',
    'confirmInfo': '_confirmInfo',
    'confirmStatus': '_confirmStatus',
    'contractCode': '内部合同Code',
    'contractId': '内部合同ID',
    'contractName': '内部合同名称',
    'contractOfflineCode': '内部合同编号',
    'contractStatus': '内部合同编号状态',
    'cpDisplayName': '所属公司显示名字',
    'cpId': '所属公司Id',
    'cpName': '所属公司名字',
    'ctime': '创建时间',
    'deDeposit': '扣减保底金',
    'deOtherAmount': '扣减其他费用',
    'divisionMethodName': '合作模式',
    'endTime': '结算结束时间',
    'id': '支付单Id',
    'isCanApprove': '可以审核',
    'liableManName': '合约负责人',
    'name': '支付单名称',
    'ogTotleAmount': '原始分成总计',
    'payTotleAmount': '实际分成合计',
    'paymentAttachments': '支付单附件',  # 支付单附件 一个包含字典的列表
    'paymentInvoiceAttachments': '_paymentInvoiceAttachments',
    'paymentReceiptAttachments': '_paymentReceiptAttachments',
    'settleFormula': '结算公式',
    'settlementCurrency': '结算货币ID',
    'settlementCurrencyStr': '结算货币名字',
    'shareAchievedAmount': '_shareAchievedAmount',
    'shareProportion': '合同分成比例',
    'spDisplayName': '结算渠道显示名字',
    'spId': '结算渠道Id',
    'spName': '结算渠道名字',
    'startTime': '结算开始时间',
    'sid': '_sid',
    'sstatus': '_sstatus',
    'shareInterval': '_shareInterval',
    'status': '状态',
    'statusStr': '当前状态名字',
    'supplierDisplayName': '供应商显示名字',
    'supplierId': '供应商ID',
    'supplierName': '供应商名字',
    'totleAmount': '实际分成合计',
    'uname': '更新用户',
    'utime': '更新时间',
    # 20241101 删除的内容
    # 'divisionMethod': '合作模式Id',
    # 20241101 添加的内容
    'divisionRuleId': '_divisionRuleId',
    'divisionModeNames': '_divisionModeNames',  # 内容是一个文本列表
    'shareProportions': '分成比例',  # 内容是一个百分比文本列表
    'bname': '_bname',
    'fname': '_fname',
    'zname': '_zname',
    'copyrightTypeRecord': '_copyrightTypeRecord',
    'copyrightTypeLyric': '_copyrightTypeLyric',
    'copyrightTypeMusic': '_copyrightTypeMusic',
    'copyrightTypeMv': '_copyrightTypeMv',
    'minPayBalance': '_minPayBalance',
    'otherFeeBalance': '_otherFeeBalance',
    'settlePaymentProofGenerationStatus': '_settlePaymentProofGenerationStatus',
}

# 歌曲列表
SONG_LIST_FIELDS = {
    'advertPublishBeginDate': '_advertPublishBeginDate',
    'advertPublishEndDate': '_advertPublishEndDate',
    'albumCode': '专辑CODE',
    'albumCopyrightOrgId': '_albumCopyrightOrgId',
    'albumCopyrightOrgName': '_albumCopyrightOrgName',
    'albumId': '专辑ID',
    'albumName': '专辑名字',
    'albumSingers': '专辑演唱者列表',  # 列表数据 None
    'albumStatus': '专辑状态',
    'arrangers': '编曲人列表',  # 列表数据
    'artistIdentities': '_artistIdentities',
    'awardRecord': '_awardRecord',
    'cd': 'CD集',
    'channelStatus': '渠道方状态',
    'cid': '创建者ID',
    'claimRemark': '_claimRemark',
    'clineOrgId': '_clineOrgId',
    'clineYear': '_clineYear',
    'cname': '创建者',
    'code': 'CODE',
    'collectionName': '_collectionName',
    'collectionTranslatedName': '_collectionTranslatedName',
    'composers': '曲作者',  # 列表数据
    'copyFromSongId': '_copyFromSongId',
    'copyrightMark': '_copyrightMark',
    'creationBackground': '歌曲创作背景',
    'ctime': '创建时间',
    'customJson': '_customJson',
    'dataSourceType': '_dataSourceType',
    'dataSourceUk': '_dataSourceUk',
    'firstPublishDate': '首次发行时间',
    'hasPublicity': '_hasPublicity',
    'id': '歌曲ID',  # 改为 song_id
    'introduction': '歌曲简介',
    'isbn': 'ISBN',
    'isrc': 'ISRC',
    'iswc': 'ISWC',
    'langTags': '歌曲语言列表',  # 列表数据
    'languageTagId': '歌曲语言ID',
    'liableManId': '_liableManId',
    'liableManName': '_liableManName',
    'lockStatus': '_lockStatus',
    'lyricCopyrightContracts': '_lyricCopyrightContracts',  # 列表数据
    'lyricCopyrightIds': '_lyricCopyrightIds',
    'lyricists': '词作者列表',  # 列表数据
    'mainTune': '_mainTune',
    'movieName': '影视名',
    'musicCopyrightContracts': '_musicCopyrightContracts',  # 列表数据
    'musicCopyrightIds': '_musicCopyrightIds',
    'name': '歌曲名称',
    'originalSingName': '_originalSingName',
    'originalSongName': '_originalSongName',
    'osSongInfo': '_osSongInfo',
    'otherTags': '歌曲标签列表',  # 列表数据
    'paymentPattern': '_paymentPattern',
    'plineOrgId': '_plineOrgId',
    'plineYear': '_plineYear',
    'presaleTime': '_presaleTime',
    'productOrgId': '制作公司ID',
    'publicityPaymentPattern': '_publicityPaymentPattern',
    'publishDate': '期望上线时间',
    'quality': '_quality',
    'reason': '_reason',
    'recordArtists': '_recordArtists',  # 列表数据
    'recordCopyrightContracts': '_recordCopyrightContracts',  # 列表数据
    'recordOrgId': '录音公司ID',
    'remixArtists': '_remixArtists',  # 列表数据
    'saleBeginTime': '销售开始时间',
    'saleEndTime': '销售结束时间',
    'salePrice': '销售价钱',
    'selfOwn': '_selfOwn',
    'sendType': '_sendType',
    'singers': '演唱者列表',  # 列表数据
    'songSource': '歌曲来源',
    'sort': '排序',
    'soundRecordingCopyrightIds': '_soundRecordingCopyrightIds',
    'source': '_source',
    'status': '状态',
    'styleTagId': '歌曲风格ID',
    'styleTags': '歌曲风格列表',  # 列表数据
    'subtitle': '歌曲副标题',
    'tmeCmlId': '_tmeCmlId',
    'tmeEpId': '_tmeEpId',
    'trackNum': '音轨号',
    'translatedName': '歌曲译名',
    'type': '类型',
    'uid': '更新用户ID',
    'uname': '更新用户',
    'uniqueName': '唯一名称',
    'upCpSongNo': '_upCpSongNo',
    'utime': '更新时间',
    'version': '版本列表',  # 列表
    'versionName': '版本名字',
    'visrc': '_visrc',
}

# 歌曲详情
SONG_DETAIL_FIELDS = {
    'advertPublishBeginDate': '_advertPublishBeginDate',
    'advertPublishEndDate': '_advertPublishEndDate',
    'albumCode': '专辑CODE',
    'albumCopyrightOrgId': '_albumCopyrightOrgId',
    'albumCopyrightOrgName': '_albumCopyrightOrgName',
    'albumId': '专辑ID',
    'albumName': '专辑名字',
    'albumSingers': '专辑演唱者列表',  # 列表数据
    'albumStatus': '专辑状态',
    'arranger': '编曲',  # 列表数据
    'arrangers': '编曲人列表',  # 列表数据
    'artistIdentities': '_artistIdentities',
    'authRegionIds': '_authRegionIds',
    'awardRecord': '_awardRecord',
    'cd': 'CD集',
    'cdId': 'CD集ID',
    'cdName': 'CD集名字',
    'cdNo': 'CD集号码',
    'channelArtists': '渠道方演唱者列表',  # 列表数据
    'channelIdInfos': '渠道方歌曲信息列表',  # 列表数据
    'channelStatus': '渠道方状态',
    'cid': '创建者ID',
    'claimRemark': '_claimRemark',
    'clineOrgDisplayName': '_clineOrgDisplayName',
    'clineOrgId': '_clineOrgId',
    'clineOrgName': '_clineOrgName',
    'clineOrgStatus': '_clineOrgStatus',
    'clineYear': '_clineYear',
    'cname': '创建者',
    'code': 'CODE',
    'collectionName': '_collectionName',
    'collectionTranslatedName': '_collectionTranslatedName',
    'composer': '曲作者',  # 列表数据
    'composers': '曲作者列表',  # 列表数据
    'copyFromSongId': '_copyFromSongId',
    'copyrightMark': '_copyrightMark',
    'creationBackground': '歌曲创作背景',
    'ctime': '创建时间',
    'customJson': '_customJson',
    'dataSourceType': '_dataSourceType',
    'dataSourceUk': '_dataSourceUk',
    'firstPublishDate': '首次发行时间',
    'hasPublicity': '_hasPublicity',
    'haveAllCopyright': '_haveAllCopyright',
    'id': '歌曲ID',  # 改为 song_id
    'introduction': '歌曲简介',
    'isbn': 'ISBN',
    'isrc': 'ISRC',
    'isrcEditFlag': '_isrcEditFlag',
    'iswc': 'ISWC',
    'langTags': '歌曲语言列表',  # 列表数据
    'languageTagId': '歌曲语言ID',
    'liableManId': '_liableManId',
    'liableManName': '_liableManName',
    'lockStatus': '_lockStatus',
    'lyricCopyrightContracts': '_lyricCopyrightContracts',  # 列表数据
    'lyricCopyrightIds': '_lyricCopyrightIds',
    'lyricist': '词作者',  # 列表数据
    'lyricists': '词作者列表',  # 列表数据
    'lyrics': '_lyrics',
    'mainTune': '_mainTune',
    'movieName': '影视名',
    'musicCopyrightContracts': '_musicCopyrightContracts',  # 列表数据
    'musicCopyrightIds': '_musicCopyrightIds',
    'name': '歌曲名称',
    'offlineDate': '_offlineDate',
    'onlineDate': '_onlineDate',
    'originalSingName': '_originalSingName',
    'originalSongName': '_originalSongName',
    'osSongInfo': '_osSongInfo',
    'otherTags': '歌曲标签列表',  # 列表数据
    'overseasLyrics': '海外歌词列表',  # 列表数据'
    'paymentPattern': '_paymentPattern',
    'plineOrgDisplayName': '_plineOrgDisplayName',
    'plineOrgId': '_plineOrgId',
    'plineOrgName': '_plineOrgName',
    'plineOrgStatus': '_plineOrgStatus',
    'plineYear': '_plineYear',
    'presaleTime': '_presaleTime',
    'producers': '制作人列表',  # 列表数据
    'productOrgId': '制作公司ID',
    'productOrgName': '制作公司',
    'productOrgStatus': '制作公司状态',
    'publicityPaymentPattern': '_publicityPaymentPattern',
    'publishDate': '期望上线时间',
    'quality': '_quality',
    'reason': '_reason',
    'recordArtists': '_recordArtists',  # 列表数据
    'recordCopyrightContracts': '_recordCopyrightContracts',  # 列表数据
    'recordOrgDisplayName': '录音公司常用名',
    'recordOrgId': '录音公司ID',
    'recordOrgName': '录音公司全称',
    'recordOrgStatus': '录音公司状态',
    'recordingCopyright': '_recordingCopyright',
    'remixArtists': '_remixArtists',  # 列表数据
    'rightPercentage': '_rightPercentage',
    'saleBeginTime': '销售开始时间',
    'saleEndTime': '销售结束时间',
    'salePrice': '销售价钱',
    'selfOwn': '_selfOwn',
    'sendType': '_sendType',
    'singers': '演唱者列表',  # 列表数据
    'songLyricCopyrights': '_songLyricCopyrights',
    'songMaterialVo': '_songMaterialVo',
    'songMusicCopyrights': '_songMusicCopyrights',
    'songProducers': '_songProducers',
    'songSource': '歌曲来源',
    'sort': '排序',
    'soundRecordingCopyrightIds': '_soundRecordingCopyrightIds',
    'source': '_source',
    'speptVos': '渠道列表',  # 列表数据
    'status': '状态',
    'styleTagId': '歌曲风格ID',
    'styleTags': '歌曲风格列表',  # 列表数据
    'subtitle': '歌曲副标题',
    'takeDown': '_takeDown',
    'tmeCmlId': '_tmeCmlId',
    'tmeEpId': '_tmeEpId',
    'tmeTrackId': 'TME音轨ID',
    'trackNum': '音轨号',
    'translatedName': '歌曲译名',
    'type': '类型',
    'uid': '更新用户ID',
    'uname': '更新用户',
    'uniqueName': '唯一名称',
    'upCpSongNo': '_upCpSongNo',
    'utime': '更新时间',
    'version': '版本列表',  # 列表
    'versionName': '版本名字',
    'visrc': '_visrc',
    'visrcEditFlag': '_visrcEditFlag',
}
