# This file was auto-generated by Fern from our API Definition.

from .resources import PageCaptureReport, PageScreenshotReport, pagecapture

__all__ = ["PageCaptureReport", "PageScreenshotReport", "pagecapture"]
