"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from .usform1040 import UsForm1040, UsForm1040TypedDict
from abbyy_document_ai.types import BaseModel
from abbyy_document_ai.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetExtractedUsForm1040FieldsRequestTypedDict(TypedDict):
    document_id: str
    r"""The id of the document"""


class GetExtractedUsForm1040FieldsRequest(BaseModel):
    document_id: Annotated[
        str,
        pydantic.Field(alias="documentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The id of the document"""


class GetExtractedUsForm1040FieldsResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    us_form1040: NotRequired[UsForm1040TypedDict]
    r"""Extracted US Form 1040 Data Response"""


class GetExtractedUsForm1040FieldsResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    us_form1040: Optional[UsForm1040] = None
    r"""Extracted US Form 1040 Data Response"""
