"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from .usformw2 import UsFormW2, UsFormW2TypedDict
from abbyy_document_ai.types import BaseModel
from abbyy_document_ai.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetExtractedUsFormW2FieldsRequestTypedDict(TypedDict):
    document_id: str
    r"""The id of the document"""


class GetExtractedUsFormW2FieldsRequest(BaseModel):
    document_id: Annotated[
        str,
        pydantic.Field(alias="documentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The id of the document"""


class GetExtractedUsFormW2FieldsResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    us_form_w2: NotRequired[UsFormW2TypedDict]
    r"""Extracted US Form W2 Data Response"""


class GetExtractedUsFormW2FieldsResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    us_form_w2: Optional[UsFormW2] = None
    r"""Extracted US Form W2 Data Response"""
