# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from th2_grpc_act_template import act_template_pb2 as th2__grpc__act__template_dot_act__template__pb2


class ActStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.placeOrderFIX = channel.unary_unary(
                '/Act/placeOrderFIX',
                request_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
                response_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.FromString,
                )
        self.placeOrderCancelRequest = channel.unary_unary(
                '/Act/placeOrderCancelRequest',
                request_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
                response_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.FromString,
                )
        self.placeOrderCancelReplaceRequest = channel.unary_unary(
                '/Act/placeOrderCancelReplaceRequest',
                request_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
                response_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.FromString,
                )
        self.sendRawMessage = channel.unary_unary(
                '/Act/sendRawMessage',
                request_serializer=th2__grpc__act__template_dot_act__template__pb2.SendRawMessageRequest.SerializeToString,
                response_deserializer=th2__grpc__act__template_dot_act__template__pb2.SendRawMessageResponse.FromString,
                )
        self.sendMessage = channel.unary_unary(
                '/Act/sendMessage',
                request_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
                response_deserializer=th2__grpc__act__template_dot_act__template__pb2.SendMessageResponse.FromString,
                )
        self.placeQuoteRequestFIX = channel.unary_unary(
                '/Act/placeQuoteRequestFIX',
                request_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
                response_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.FromString,
                )
        self.placeQuoteFIX = channel.unary_unary(
                '/Act/placeQuoteFIX',
                request_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
                response_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.FromString,
                )
        self.placeOrderMassCancelRequestFIX = channel.unary_unary(
                '/Act/placeOrderMassCancelRequestFIX',
                request_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
                response_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.FromString,
                )
        self.placeQuoteCancelFIX = channel.unary_unary(
                '/Act/placeQuoteCancelFIX',
                request_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
                response_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.FromString,
                )
        self.placeQuoteResponseFIX = channel.unary_unary(
                '/Act/placeQuoteResponseFIX',
                request_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
                response_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.FromString,
                )
        self.placeSecurityStatusRequest = channel.unary_unary(
                '/Act/placeSecurityStatusRequest',
                request_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
                response_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.FromString,
                )
        self.multiSendMessage = channel.unary_unary(
                '/Act/multiSendMessage',
                request_serializer=th2__grpc__act__template_dot_act__template__pb2.MultiSendRequest.SerializeToString,
                response_deserializer=th2__grpc__act__template_dot_act__template__pb2.SendMessageResponse.FromString,
                )


class ActServicer(object):
    """Missing associated documentation comment in .proto file."""

    def placeOrderFIX(self, request, context):
        """This action executes next steps:
        1) Registers checkpoint in Verifier microservice
        2) Sends passed message as is to Connectivity microservice
        3) Waits Execution Report or Business Message Reject with the same ClOrdID as in passed message
        from Connectivity microservice
        4) Returns the message repose and the Checkpoint 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def placeOrderCancelRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def placeOrderCancelReplaceRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendRawMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendMessage(self, request, context):
        """Send fix message without response awaiting 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def placeQuoteRequestFIX(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def placeQuoteFIX(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def placeOrderMassCancelRequestFIX(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def placeQuoteCancelFIX(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def placeQuoteResponseFIX(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def placeSecurityStatusRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def multiSendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'placeOrderFIX': grpc.unary_unary_rpc_method_handler(
                    servicer.placeOrderFIX,
                    request_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.FromString,
                    response_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.SerializeToString,
            ),
            'placeOrderCancelRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.placeOrderCancelRequest,
                    request_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.FromString,
                    response_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.SerializeToString,
            ),
            'placeOrderCancelReplaceRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.placeOrderCancelReplaceRequest,
                    request_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.FromString,
                    response_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.SerializeToString,
            ),
            'sendRawMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.sendRawMessage,
                    request_deserializer=th2__grpc__act__template_dot_act__template__pb2.SendRawMessageRequest.FromString,
                    response_serializer=th2__grpc__act__template_dot_act__template__pb2.SendRawMessageResponse.SerializeToString,
            ),
            'sendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.sendMessage,
                    request_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.FromString,
                    response_serializer=th2__grpc__act__template_dot_act__template__pb2.SendMessageResponse.SerializeToString,
            ),
            'placeQuoteRequestFIX': grpc.unary_unary_rpc_method_handler(
                    servicer.placeQuoteRequestFIX,
                    request_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.FromString,
                    response_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.SerializeToString,
            ),
            'placeQuoteFIX': grpc.unary_unary_rpc_method_handler(
                    servicer.placeQuoteFIX,
                    request_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.FromString,
                    response_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.SerializeToString,
            ),
            'placeOrderMassCancelRequestFIX': grpc.unary_unary_rpc_method_handler(
                    servicer.placeOrderMassCancelRequestFIX,
                    request_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.FromString,
                    response_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.SerializeToString,
            ),
            'placeQuoteCancelFIX': grpc.unary_unary_rpc_method_handler(
                    servicer.placeQuoteCancelFIX,
                    request_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.FromString,
                    response_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.SerializeToString,
            ),
            'placeQuoteResponseFIX': grpc.unary_unary_rpc_method_handler(
                    servicer.placeQuoteResponseFIX,
                    request_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.FromString,
                    response_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.SerializeToString,
            ),
            'placeSecurityStatusRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.placeSecurityStatusRequest,
                    request_deserializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.FromString,
                    response_serializer=th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.SerializeToString,
            ),
            'multiSendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.multiSendMessage,
                    request_deserializer=th2__grpc__act__template_dot_act__template__pb2.MultiSendRequest.FromString,
                    response_serializer=th2__grpc__act__template_dot_act__template__pb2.SendMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Act', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Act(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def placeOrderFIX(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Act/placeOrderFIX',
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def placeOrderCancelRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Act/placeOrderCancelRequest',
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def placeOrderCancelReplaceRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Act/placeOrderCancelReplaceRequest',
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendRawMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Act/sendRawMessage',
            th2__grpc__act__template_dot_act__template__pb2.SendRawMessageRequest.SerializeToString,
            th2__grpc__act__template_dot_act__template__pb2.SendRawMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Act/sendMessage',
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
            th2__grpc__act__template_dot_act__template__pb2.SendMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def placeQuoteRequestFIX(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Act/placeQuoteRequestFIX',
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def placeQuoteFIX(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Act/placeQuoteFIX',
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def placeOrderMassCancelRequestFIX(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Act/placeOrderMassCancelRequestFIX',
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def placeQuoteCancelFIX(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Act/placeQuoteCancelFIX',
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def placeQuoteResponseFIX(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Act/placeQuoteResponseFIX',
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def placeSecurityStatusRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Act/placeSecurityStatusRequest',
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageRequest.SerializeToString,
            th2__grpc__act__template_dot_act__template__pb2.PlaceMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def multiSendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Act/multiSendMessage',
            th2__grpc__act__template_dot_act__template__pb2.MultiSendRequest.SerializeToString,
            th2__grpc__act__template_dot_act__template__pb2.SendMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
