# Generated by Django 4.2.13 on 2024-10-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "djangoldp_tamis",
            "0016_remove_format_identifiants_format_identifier_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="editorialwork",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="editorialwork",
            name="alternate_title",
            field=models.CharField(blank=True, default="", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="editorialwork",
            name="identifiants",
            field=models.ManyToManyField(blank=True, to="djangoldp_tamis.identifiant"),
        ),
    ]
