
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-16T14:58:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc78bec7c2909acf1f652dcaefcd9b5587ceb94e",
 "version": "v0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
