from _typeshed import Incomplete

kbool: int
kuint8: int
kint8: int
kint16: int
kint32: int
kint64: int
kfloat32: int
kfloat64: int
kcomplex64: int
kcomplex128: int
F_DTYPE = kfloat32
D_DTYPE = kfloat64
C_DTYPE = kcomplex64
Z_DTYPE = kcomplex128
vqnet_complex_dtypes: Incomplete
vqnet_float_dtypes: Incomplete

def complex_dtype_to_float_dtype(dtype): ...
def float_dtype_to_complex_dtype(dtype): ...
def get_xtensor_dtype_str(dtype_int): ...
def get_readable_dtype_str(dtype_int):
    """
    get data type string for data type
    """
def dtype_map_from_numpy(dtype_np): ...

dtype_map: Incomplete
vqnet_2_np_dtype = dtype_map

class Defualt_QTensor_Dtype:
    default_dtype: Incomplete
    def __init__(self) -> None: ...
    def set_default_dtype(self, d) -> None: ...
    def get_default_dtype(self): ...

class Defualt_xtensor_Dtype:
    default_dtype: Incomplete
    def __init__(self) -> None: ...
    def set_default_dtype(self, d) -> None: ...
    def get_default_dtype(self): ...

qtensor_default: Incomplete
xtensor_default: Incomplete

def set_default_dtype(d) -> None: ...
def get_default_dtype(): ...
def set_xtensor_default_dtype(d) -> None: ...
def get_xtensor_default_dtype(): ...
def get_xtensor_dtype(dtype_enum): ...
def valid_param_dtype(dtype): ...
