# Generated by Django 4.2.16 on 2024-10-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_tamis', '0013_prestation_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='type',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
