# Auto-generated __init__.py

# Version of the pyfunc2 package
import sys
sys.path.append('../')
from ._version import __version__

# Import necessary modules and functions here
from change_default_branch import change_default_branch
from get_domain_from_page import get_domain_from_page
from update_github_pages import update_github_pages
from get_param_from_repo import get_param_from_repo
from enable_github_pages import enable_github_pages
from clone_repo_from_org import clone_repo_from_org
from get_repos_from_org import get_repos_from_org
from get_owner_json import get_owner_json
from create_notexisting_folder import create_notexisting_folder
from set_github_pages_domain import set_github_pages_domain
from rename_branch_on_github import rename_branch_on_github
from delete_branch_on_github import delete_branch_on_github
from update_repo_on_github import update_repo_on_github
from has_valid_credentials import has_valid_credentials
from create_repo_on_github import create_repo_on_github
from create_project_in_org import create_project_in_org
from update_default_branch_on_github import update_default_branch_on_github
from create_repo_on_github_and_local import create_repo_on_github_and_local
from set_domain_on_github_org_pages import set_domain_on_github_org_pages
from update_organization_on_github import update_organization_on_github
from create_organization_on_github import create_organization_on_github
from configure_github_pages_branch import set_page_on_github_org_repos
from update_organization_projects import update_organization_projects
from new_organization_scenario import new_organization_scenario
from get_repository_list_wtih_github_pages import get_repository_list_wtih_github_pages
from create_repo_on_not_git_repo_folder import create_repo_on_not_git_repo_folder
from getHeaders2 import getHeaders2
from getHeaders import getHeaders
from get_repos import get_repos
from defaults import defaults

# Public API of the package
__all__ = [change_default_branch, get_domain_from_page, update_github_pages, get_param_from_repo, enable_github_pages, clone_repo_from_org, get_repos_from_org, get_owner_json, create_notexisting_folder, set_github_pages_domain, rename_branch_on_github, delete_branch_on_github, update_repo_on_github, has_valid_credentials, create_repo_on_github, create_project_in_org, update_default_branch_on_github, create_repo_on_github_and_local, set_domain_on_github_org_pages, update_organization_on_github, create_organization_on_github, set_page_on_github_org_repos, update_organization_projects, new_organization_scenario, get_repository_list_wtih_github_pages, create_repo_on_not_git_repo_folder, getHeaders2, getHeaders, get_repos, defaults]