from gadopenapiconverter.mappers.python import MAPPING_PYTHON_MODULE_TO_DATAMODEL
from gadopenapiconverter.mappers.specification import MAPPING_TYPE_SPECIFICATION_TO_PYTHON

__all__ = ["MAPPING_TYPE_SPECIFICATION_TO_PYTHON", "MAPPING_PYTHON_MODULE_TO_DATAMODEL"]
