"""Default values for numbers and brightness analysis"""

DEFAULT_BACKGROUND = 0
DEFAULT_SEGMENT = False
DEFAULT_DIAMETER = 100
DEFAULT_FLOW_THRESHOLD = 0.4
DEFAULT_CELLPROB_THRESHOLD = 3
DEFAULT_ANALYSIS = False
DEFAULT_ERODE = 2