# generated by datamodel-codegen:
#   filename:  properties_directory/structural/patterns/special_bond.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Name(Enum):
    special_bond = "special_bond"


class AtomicId(BaseModel):
    isConnector: Optional[bool] = None
    """
    whether atom connects to atoms outside of functional group.
    """
    id: Optional[int] = None
    """
    integer id of this entry
    """


class SpecialBondPatternSchema(BaseModel):
    name: Optional[Name] = None
    atoms: Optional[List[AtomicId]] = Field(None, title="atomic ids")
    """
    array of objects containing integer id each
    """
