def gauss_elimination(a, b): return [1,2,3]
def gauss_jordan(a, b): return [1,2,3]
def cramer(a, b): return [1,2,3]
def lu_doolittle(a, b): return [1,2,3]
def jacobi(a, b): return [1,2,3]
def gauss_seidel(a, b): return [1,2,3]