from enum import Enum

class RabbitMQRoutingKey(str, Enum):
    AUTH_OTP = 'AUTH_OTP'
    AUTH_LOGIN = 'AUTH_LOGIN'
    AUTH_DATA = 'AUTH_DATA'
    POSTS_CREATE = 'POSTS_CREATE'
    POSTS_LIST = 'POSTS_LIST'
    POSTS_DELETE = 'POSTS_DELETE'
    POSTS_UPDATE = 'POSTS_UPDATE'
    ORDERS_LIST = 'ORDERS_LIST'
    ORDERS_LABELS_GET = 'ORDERS_LABELS_GET'
    MESSAGES_INBOX_GET = 'MESSAGES_INBOX_GET'
    MESSAGES_CONVERSATIONS_GET = 'MESSAGES_CONVERSATIONS_GET'
    MESSAGES_CONVERSATIONS_OFFERS_CREATE = 'MESSAGES_CONVERSATIONS_OFFERS_CREATE'
