
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-16T22:10:07+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b5fb8bd0d75756eb7c531bba7b50a9d73401626b",
 "version": "0.0.1.dev0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
