
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-15T10:02:11+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1d72ed68ae84c3612b4a7eceebf7950ae0a4eeea",
 "version": "0.1.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
