# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orin3_grpc/message/orin3/provider/v1/orin3_job.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'orin3_grpc/message/orin3/provider/v1/orin3_job.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from orin3_grpc.message.orin3.provider.v1 import orin3_common_type_pb2 as orin3__grpc_dot_message_dot_orin3_dot_provider_dot_v1_dot_orin3__common__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4orin3_grpc/message/orin3/provider/v1/orin3_job.proto\x12\x16Message.ORiN3.Provider\x1a<orin3_grpc/message/orin3/provider/v1/orin3_common_type.proto\"]\n\x18GetStandardOutputRequest\x12\x35\n\x06\x63ommon\x18\x01 \x01(\x0b\x32%.Message.ORiN3.Provider.CommonRequest\x12\n\n\x02id\x18\x02 \x01(\x0c\"c\n\x19GetStandardOutputResponse\x12\x36\n\x06\x63ommon\x18\x01 \x01(\x0b\x32&.Message.ORiN3.Provider.CommonResponse\x12\x0e\n\x06output\x18\x02 \x01(\t\"\\\n\x17GetStandardErrorRequest\x12\x35\n\x06\x63ommon\x18\x01 \x01(\x0b\x32%.Message.ORiN3.Provider.CommonRequest\x12\n\n\x02id\x18\x02 \x01(\x0c\"a\n\x18GetStandardErrorResponse\x12\x36\n\x06\x63ommon\x18\x01 \x01(\x0b\x32&.Message.ORiN3.Provider.CommonResponse\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"U\n\x10GetResultRequest\x12\x35\n\x06\x63ommon\x18\x01 \x01(\x0b\x32%.Message.ORiN3.Provider.CommonRequest\x12\n\n\x02id\x18\x02 \x01(\x0c\"s\n\x11GetResultResponse\x12\x36\n\x06\x63ommon\x18\x01 \x01(\x0b\x32&.Message.ORiN3.Provider.CommonResponse\x12\x0e\n\x06result\x18\x02 \x01(\x0c\x12\x16\n\x0eis_null_result\x18\x03 \x01(\x08\x32\xdf\x02\n\nJobService\x12x\n\x11GetStandardOutput\x12\x30.Message.ORiN3.Provider.GetStandardOutputRequest\x1a\x31.Message.ORiN3.Provider.GetStandardOutputResponse\x12u\n\x10GetStandardError\x12/.Message.ORiN3.Provider.GetStandardErrorRequest\x1a\x30.Message.ORiN3.Provider.GetStandardErrorResponse\x12`\n\tGetResult\x12(.Message.ORiN3.Provider.GetResultRequest\x1a).Message.ORiN3.Provider.GetResultResponseBa\xaa\x02+Message.ORiN3.Provider.V1.AutoGenerated.Job\xea\x02\x30Message::ORiN3::Provider::V1::AutoGenerated::Jobb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orin3_grpc.message.orin3.provider.v1.orin3_job_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002+Message.ORiN3.Provider.V1.AutoGenerated.Job\352\0020Message::ORiN3::Provider::V1::AutoGenerated::Job'
  _globals['_GETSTANDARDOUTPUTREQUEST']._serialized_start=142
  _globals['_GETSTANDARDOUTPUTREQUEST']._serialized_end=235
  _globals['_GETSTANDARDOUTPUTRESPONSE']._serialized_start=237
  _globals['_GETSTANDARDOUTPUTRESPONSE']._serialized_end=336
  _globals['_GETSTANDARDERRORREQUEST']._serialized_start=338
  _globals['_GETSTANDARDERRORREQUEST']._serialized_end=430
  _globals['_GETSTANDARDERRORRESPONSE']._serialized_start=432
  _globals['_GETSTANDARDERRORRESPONSE']._serialized_end=529
  _globals['_GETRESULTREQUEST']._serialized_start=531
  _globals['_GETRESULTREQUEST']._serialized_end=616
  _globals['_GETRESULTRESPONSE']._serialized_start=618
  _globals['_GETRESULTRESPONSE']._serialized_end=733
  _globals['_JOBSERVICE']._serialized_start=736
  _globals['_JOBSERVICE']._serialized_end=1087
# @@protoc_insertion_point(module_scope)
