# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orin3_grpc/message/orin3/provider/v1/orin3_child.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'orin3_grpc/message/orin3/provider/v1/orin3_child.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from orin3_grpc.message.orin3.provider.v1 import orin3_common_type_pb2 as orin3__grpc_dot_message_dot_orin3_dot_provider_dot_v1_dot_orin3__common__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6orin3_grpc/message/orin3/provider/v1/orin3_child.proto\x12\x16Message.ORiN3.Provider\x1a<orin3_grpc/message/orin3/provider/v1/orin3_common_type.proto\"R\n\rDeleteRequest\x12\x35\n\x06\x63ommon\x18\x01 \x01(\x0b\x32%.Message.ORiN3.Provider.CommonRequest\x12\n\n\x02id\x18\x02 \x01(\x0c\"H\n\x0e\x44\x65leteResponse\x12\x36\n\x06\x63ommon\x18\x01 \x01(\x0b\x32&.Message.ORiN3.Provider.CommonResponse2g\n\x0c\x43hildService\x12W\n\x06\x44\x65lete\x12%.Message.ORiN3.Provider.DeleteRequest\x1a&.Message.ORiN3.Provider.DeleteResponseBe\xaa\x02-Message.ORiN3.Provider.V1.AutoGenerated.Child\xea\x02\x32Message::ORiN3::Provider::V1::AutoGenerated::Childb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orin3_grpc.message.orin3.provider.v1.orin3_child_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002-Message.ORiN3.Provider.V1.AutoGenerated.Child\352\0022Message::ORiN3::Provider::V1::AutoGenerated::Child'
  _globals['_DELETEREQUEST']._serialized_start=144
  _globals['_DELETEREQUEST']._serialized_end=226
  _globals['_DELETERESPONSE']._serialized_start=228
  _globals['_DELETERESPONSE']._serialized_end=300
  _globals['_CHILDSERVICE']._serialized_start=302
  _globals['_CHILDSERVICE']._serialized_end=405
# @@protoc_insertion_point(module_scope)
