
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-17T15:27:41-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2df5ffc6d7bc1664ea86bb77d525f2d7ec849643",
 "version": "2025.4.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
