"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from .taxireceipt import TaxiReceipt, TaxiReceiptTypedDict
from abbyy_document_ai.types import BaseModel
from abbyy_document_ai.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetExtractedTaxiReceiptFieldsRequestTypedDict(TypedDict):
    document_id: str
    r"""The id of the document"""


class GetExtractedTaxiReceiptFieldsRequest(BaseModel):
    document_id: Annotated[
        str,
        pydantic.Field(alias="documentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The id of the document"""


class GetExtractedTaxiReceiptFieldsResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    taxi_receipt: NotRequired[TaxiReceiptTypedDict]
    r"""Extracted Taxi Receipt Data Response"""


class GetExtractedTaxiReceiptFieldsResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    taxi_receipt: Optional[TaxiReceipt] = None
    r"""Extracted Taxi Receipt Data Response"""
