"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from .utilitybill import UtilityBill, UtilityBillTypedDict
from abbyy_document_ai.types import BaseModel
from abbyy_document_ai.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetExtractedUtilityBillFieldsRequestTypedDict(TypedDict):
    document_id: str
    r"""The id of the document"""


class GetExtractedUtilityBillFieldsRequest(BaseModel):
    document_id: Annotated[
        str,
        pydantic.Field(alias="documentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The id of the document"""


class GetExtractedUtilityBillFieldsResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    utility_bill: NotRequired[UtilityBillTypedDict]
    r"""Extracted Utility Bill Data Response"""


class GetExtractedUtilityBillFieldsResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    utility_bill: Optional[UtilityBill] = None
    r"""Extracted Utility Bill Data Response"""
