"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customsdeclaration import CustomsDeclaration, CustomsDeclarationTypedDict
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from abbyy_document_ai.types import BaseModel
from abbyy_document_ai.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetExtractedCustomsDeclarationFieldsRequestTypedDict(TypedDict):
    document_id: str
    r"""The id of the document"""


class GetExtractedCustomsDeclarationFieldsRequest(BaseModel):
    document_id: Annotated[
        str,
        pydantic.Field(alias="documentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The id of the document"""


class GetExtractedCustomsDeclarationFieldsResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    customs_declaration: NotRequired[CustomsDeclarationTypedDict]
    r"""Extracted Customs Declaration Data Response"""


class GetExtractedCustomsDeclarationFieldsResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    customs_declaration: Optional[CustomsDeclaration] = None
    r"""Extracted Customs Declaration Data Response"""
