"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .commercialinvoice import CommercialInvoice, CommercialInvoiceTypedDict
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from abbyy_document_ai.types import BaseModel
from abbyy_document_ai.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetExtractedCommercialInvoiceFieldsRequestTypedDict(TypedDict):
    document_id: str
    r"""The id of the document"""


class GetExtractedCommercialInvoiceFieldsRequest(BaseModel):
    document_id: Annotated[
        str,
        pydantic.Field(alias="documentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The id of the document"""


class GetExtractedCommercialInvoiceFieldsResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    commercial_invoice: NotRequired[CommercialInvoiceTypedDict]
    r"""Extracted Commercial Invoice Data Response"""


class GetExtractedCommercialInvoiceFieldsResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    commercial_invoice: Optional[CommercialInvoice] = None
    r"""Extracted Commercial Invoice Data Response"""
