"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .deliverynote import DeliveryNote, DeliveryNoteTypedDict
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from abbyy_document_ai.types import BaseModel
from abbyy_document_ai.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetExtractedDeliveryNoteFieldsRequestTypedDict(TypedDict):
    document_id: str
    r"""The id of the document"""


class GetExtractedDeliveryNoteFieldsRequest(BaseModel):
    document_id: Annotated[
        str,
        pydantic.Field(alias="documentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The id of the document"""


class GetExtractedDeliveryNoteFieldsResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    delivery_note: NotRequired[DeliveryNoteTypedDict]
    r"""Extracted Delivery Note Data Response"""


class GetExtractedDeliveryNoteFieldsResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    delivery_note: Optional[DeliveryNote] = None
    r"""Extracted Delivery Note Data Response"""
