
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-18T01:32:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4558357177a48b8af99cf60f58635556daf0416b",
 "version": "4.109"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
