# generated by datamodel-codegen:
#   filename:  sprotty/actions/requestModel.json
#   timestamp: 2025-04-17T11:51:34+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel

from .action import Action


class Kind(Enum):
    requestModel = 'requestModel'


class DiagramType(Enum):
    keith_diagram = 'keith-diagram'


class Options(BaseModel):
    needsClientLayout: Optional[bool] = None
    needsServerLayout: Optional[bool] = None
    sourceUri: Optional[str] = None
    diagramType: Optional[DiagramType] = None


class RequestModel(Action):
    kind: Optional[Kind] = 'requestModel'
    options: Options
    requestId: str
