# Generated by Django 4.2.16 on 2024-10-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_tamis', '0010_remove_asset_identifier_remove_asset_issuer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='identifiants',
        ),
        migrations.RemoveField(
            model_name='audiotrack',
            name='identifiants',
        ),
        migrations.RemoveField(
            model_name='format',
            name='identifiants',
        ),
        migrations.RemoveField(
            model_name='mediaresource',
            name='identifiants',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='identifiants',
        ),
        migrations.RemoveField(
            model_name='season',
            name='identifiants',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='identifiants',
        ),
        migrations.RemoveField(
            model_name='track',
            name='identifiants',
        ),
        migrations.RemoveField(
            model_name='videotrack',
            name='identifiants',
        ),
        migrations.AddField(
            model_name='asset',
            name='identifiants',
            field=models.ManyToManyField(blank=True, to='djangoldp_tamis.identifiant'),
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='identifiants',
            field=models.ManyToManyField(blank=True, to='djangoldp_tamis.identifiant'),
        ),
        migrations.AddField(
            model_name='format',
            name='identifiants',
            field=models.ManyToManyField(blank=True, to='djangoldp_tamis.identifiant'),
        ),
        migrations.AddField(
            model_name='mediaresource',
            name='identifiants',
            field=models.ManyToManyField(blank=True, to='djangoldp_tamis.identifiant'),
        ),
        migrations.AddField(
            model_name='programme',
            name='identifiants',
            field=models.ManyToManyField(blank=True, to='djangoldp_tamis.identifiant'),
        ),
        migrations.AddField(
            model_name='season',
            name='identifiants',
            field=models.ManyToManyField(blank=True, to='djangoldp_tamis.identifiant'),
        ),
        migrations.AddField(
            model_name='serie',
            name='identifiants',
            field=models.ManyToManyField(blank=True, to='djangoldp_tamis.identifiant'),
        ),
        migrations.AddField(
            model_name='track',
            name='identifiants',
            field=models.ManyToManyField(blank=True, to='djangoldp_tamis.identifiant'),
        ),
        migrations.AddField(
            model_name='videotrack',
            name='identifiants',
            field=models.ManyToManyField(blank=True, to='djangoldp_tamis.identifiant'),
        ),
    ]
