# generated by datamodel-codegen:
#   filename:  properties_directory/structural/basis/atomic_coordinates.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field


class Name(Enum):
    atomic_coordinates = "atomic_coordinates"


class AtomicCoordinate(BaseModel):
    id: Optional[float] = None
    value: Optional[Union[List[float], List[bool]]] = Field(None, title="vector schema")


class Units(Enum):
    km = "km"
    m = "m"
    cm = "cm"
    mm = "mm"
    um = "um"
    nm = "nm"
    angstrom = "angstrom"
    a_u_ = "a.u."
    bohr = "bohr"
    pm = "pm"


class AtomicCoordinates(BaseModel):
    name: Optional[Name] = None
    values: Optional[List[AtomicCoordinate]] = None
    units: Optional[Units] = None
