# generated by datamodel-codegen:
#   filename:  properties_directory/structural/basis/atomic_element.json
#   version:   0.28.5

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class AtomicElements(BaseModel):
    id: float
    value: str
    occurrence: Optional[float] = None
    """
    Occurrence is for fractional occupations
    """
    oxidationState: Optional[float] = None
