from collections.abc import Iterator

class CellGroup:
    def __init__(self, cells) -> None: ...
    @property
    def cells(self) -> list[tuple[float, float, float, float]]: ...

class TableRow(CellGroup): ...

class Table:
    @property
    def bbox(self) -> tuple[float, float, float, float]: ...
    def extract(self) -> list[list[str | None]]: ...
    @property
    def rows(self) -> list[TableRow]: ...

class TableFinder:
    def __iter__(self) -> Iterator[Table]: ...
