
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-16T14:42:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "005964d7d6a10463bffc0c07084e852e91028a21",
 "version": "1.2.52"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
