from .checkpipe import Pipe as Pipe
from .checkpipe import OfIter as OfIter
from .checkpipe import OfStr as OfStr
from .checkpipe import OfList as OfList
from .checkpipe import Of as Of
from .checkpipe import OfResult as OfResult
from .checkpipe import OfResultIter as OfResultIter
from .checkpipe import OfOptionalIter as OfOptionalIter
from .checkpipe import to_records as to_records
from .checkpipe import stop_iter as stop_iter
from .checkpipe import tup2_unpack as tup2_unpack
from .checkpipe import tup3_unpack as tup3_unpack
from .checkpipe import tup4_unpack as tup4_unpack
from .checkpipe import tup5_unpack as tup5_unpack
from .checkpipe import tup6_unpack as tup6_unpack
from .checkpipe import tup7_unpack as tup7_unpack
from .checkpipe import tup8_unpack as tup8_unpack
from .checkpipe import tup2_right_tup2_flatten as tup2_right_tup2_flatten
from .checkpipe import tup2_right_tup3_flatten as tup2_right_tup3_flatten
from .checkpipe import tup2_right_tup4_flatten as tup2_right_tup4_flatten
from .checkpipe import tup2_right_tup5_flatten as tup2_right_tup5_flatten
from .checkpipe import tup2_right_tup6_flatten as tup2_right_tup6_flatten
from .checkpipe import tup2_right_tup7_flatten as tup2_right_tup7_flatten