
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-17T13:27:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ecea83c4686cc9de606942adce1dfbe26f551111",
 "version": "0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
