# Generated by Django 4.2.13 on 2024-10-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangoldp_tamis", "0014_prestation_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prestation",
            name="devis_id",
        ),
    ]
