# Generated by Django 4.2.13 on 2024-10-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoldp_tamis", "0015_remove_prestation_devis_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="format",
            name="identifiants",
        ),
        migrations.AddField(
            model_name="format",
            name="identifier",
            field=models.CharField(blank=True, default="", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="mediaresource",
            name="file_size",
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
