# coding: utf-8

"""
    Ambient API

     This API provides access to Ambient services. It is designed to be used by Ambient applications and services. 

    The version of the OpenAPI document: 0.8.2
    Contact: jose@ambientlabscomputing.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ambient_backend_api_client.models.user_role_enum import UserRoleEnum

class TestUserRoleEnum(unittest.TestCase):
    """UserRoleEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserRoleEnum(self):
        """Test UserRoleEnum"""
        # inst = UserRoleEnum()

if __name__ == '__main__':
    unittest.main()
