# coding: utf-8

"""
    Ambient API

     This API provides access to Ambient services. It is designed to be used by Ambient applications and services. 

    The version of the OpenAPI document: 0.8.2
    Contact: jose@ambientlabscomputing.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ambient_backend_api_client.models.set_node_advertised_interface_request import SetNodeAdvertisedInterfaceRequest

class TestSetNodeAdvertisedInterfaceRequest(unittest.TestCase):
    """SetNodeAdvertisedInterfaceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetNodeAdvertisedInterfaceRequest:
        """Test SetNodeAdvertisedInterfaceRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetNodeAdvertisedInterfaceRequest`
        """
        model = SetNodeAdvertisedInterfaceRequest()
        if include_optional:
            return SetNodeAdvertisedInterfaceRequest(
                node_id = 56,
                advertised_interface_id = 56,
                advertised_interface_ipv4 = ''
            )
        else:
            return SetNodeAdvertisedInterfaceRequest(
                node_id = 56,
        )
        """

    def testSetNodeAdvertisedInterfaceRequest(self):
        """Test SetNodeAdvertisedInterfaceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
