# coding: utf-8

"""
    Ambient API

     This API provides access to Ambient services. It is designed to be used by Ambient applications and services. 

    The version of the OpenAPI document: 0.8.2
    Contact: jose@ambientlabscomputing.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ambient_backend_api_client.models.service_list import ServiceList

class TestServiceList(unittest.TestCase):
    """ServiceList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceList:
        """Test ServiceList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceList`
        """
        model = ServiceList()
        if include_optional:
            return ServiceList(
                count = 56,
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                results = [
                    ambient_backend_api_client.models.service.Service(
                        id = 56, 
                        name = '', 
                        resource_type = null, 
                        description = '', 
                        org_id = 56, 
                        user_id = 56, 
                        desired_state = null, 
                        requested_service_spec = ambient_backend_api_client.models.requested_service_spec.RequestedServiceSpec(
                            id = 56, 
                            service_id = 56, 
                            image = '', 
                            tags = [
                                ''
                                ], 
                            ports = [
                                ''
                                ], 
                            replicas = 56, 
                            labels = [
                                ''
                                ], 
                            env_vars = [
                                ''
                                ], 
                            hostname = '', 
                            mounts = [
                                ''
                                ], 
                            networks = [
                                ''
                                ], ), )
                    ]
            )
        else:
            return ServiceList(
                count = 56,
                results = [
                    ambient_backend_api_client.models.service.Service(
                        id = 56, 
                        name = '', 
                        resource_type = null, 
                        description = '', 
                        org_id = 56, 
                        user_id = 56, 
                        desired_state = null, 
                        requested_service_spec = ambient_backend_api_client.models.requested_service_spec.RequestedServiceSpec(
                            id = 56, 
                            service_id = 56, 
                            image = '', 
                            tags = [
                                ''
                                ], 
                            ports = [
                                ''
                                ], 
                            replicas = 56, 
                            labels = [
                                ''
                                ], 
                            env_vars = [
                                ''
                                ], 
                            hostname = '', 
                            mounts = [
                                ''
                                ], 
                            networks = [
                                ''
                                ], ), )
                    ],
        )
        """

    def testServiceList(self):
        """Test ServiceList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
