# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ambient_backend_api_client.models.owner_type_enum import OwnerTypeEnum

class TestOwnerTypeEnum(unittest.TestCase):
    """OwnerTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOwnerTypeEnum(self):
        """Test OwnerTypeEnum"""
        # inst = OwnerTypeEnum()

if __name__ == '__main__':
    unittest.main()
