# coding: utf-8

"""
    Ambient API

     This API provides access to Ambient services. It is designed to be used by Ambient applications and services. 

    The version of the OpenAPI document: 0.8.2
    Contact: jose@ambientlabscomputing.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ambient_backend_api_client.api.nodes_api import NodesApi


class TestNodesApi(unittest.IsolatedAsyncioTestCase):
    """NodesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = NodesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_node_nodes_post(self) -> None:
        """Test case for create_node_nodes_post

        Create Node
        """
        pass

    async def test_delete_node_nodes_node_id_delete(self) -> None:
        """Test case for delete_node_nodes_node_id_delete

        Delete Node
        """
        pass

    async def test_get_node_advertised_interface_nodes_node_id_interfaces_advertised_get(self) -> None:
        """Test case for get_node_advertised_interface_nodes_node_id_interfaces_advertised_get

        Get Node Advertised Interface
        """
        pass

    async def test_get_node_certificate_nodes_node_id_certificate_get(self) -> None:
        """Test case for get_node_certificate_nodes_node_id_certificate_get

        Get Node Certificate
        """
        pass

    async def test_get_node_interfaces_nodes_node_id_interfaces_get(self) -> None:
        """Test case for get_node_interfaces_nodes_node_id_interfaces_get

        Get Node Interfaces
        """
        pass

    async def test_get_node_nodes_node_id_get(self) -> None:
        """Test case for get_node_nodes_node_id_get

        Get Node
        """
        pass

    async def test_get_node_panel_data_nodes_panel_data_get(self) -> None:
        """Test case for get_node_panel_data_nodes_panel_data_get

        Get Node Panel Data
        """
        pass

    async def test_get_node_services_nodes_node_id_services_get(self) -> None:
        """Test case for get_node_services_nodes_node_id_services_get

        Get Node Services
        """
        pass

    async def test_get_nodes_nodes_get(self) -> None:
        """Test case for get_nodes_nodes_get

        Get Nodes
        """
        pass

    async def test_put_node_nodes_node_id_put(self) -> None:
        """Test case for put_node_nodes_node_id_put

        Put Node
        """
        pass

    async def test_set_node_advertised_interface_nodes_set_advertised_interface_post(self) -> None:
        """Test case for set_node_advertised_interface_nodes_set_advertised_interface_post

        Set Node Advertised Interface
        """
        pass

    async def test_update_node_nodes_node_id_patch(self) -> None:
        """Test case for update_node_nodes_node_id_patch

        Update Node
        """
        pass


if __name__ == '__main__':
    unittest.main()
