# coding: utf-8

"""
    Ambient API

     This API provides access to Ambient services. It is designed to be used by Ambient applications and services. 

    The version of the OpenAPI document: 0.8.2
    Contact: jose@ambientlabscomputing.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ambient_backend_api_client.api.clusters_api import ClustersApi


class TestClustersApi(unittest.IsolatedAsyncioTestCase):
    """ClustersApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ClustersApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_add_nodes_to_cluster_clusters_cluster_id_nodes_post(self) -> None:
        """Test case for add_nodes_to_cluster_clusters_cluster_id_nodes_post

        Add Nodes To Cluster
        """
        pass

    async def test_create_cluster_clusters_post(self) -> None:
        """Test case for create_cluster_clusters_post

        Create Cluster
        """
        pass

    async def test_delete_cluster_clusters_cluster_id_delete(self) -> None:
        """Test case for delete_cluster_clusters_cluster_id_delete

        Delete Cluster
        """
        pass

    async def test_get_cluster_clusters_cluster_id_get(self) -> None:
        """Test case for get_cluster_clusters_cluster_id_get

        Get Cluster
        """
        pass

    async def test_get_cluster_nodes_clusters_cluster_id_nodes_get(self) -> None:
        """Test case for get_cluster_nodes_clusters_cluster_id_nodes_get

        Get Cluster Nodes
        """
        pass

    async def test_get_clusters_clusters_get(self) -> None:
        """Test case for get_clusters_clusters_get

        Get Clusters
        """
        pass

    async def test_remove_nodes_from_cluster_clusters_cluster_id_nodes_delete(self) -> None:
        """Test case for remove_nodes_from_cluster_clusters_cluster_id_nodes_delete

        Remove Nodes From Cluster
        """
        pass

    async def test_update_cluster_clusters_cluster_id_put(self) -> None:
        """Test case for update_cluster_clusters_cluster_id_put

        Update Cluster
        """
        pass


if __name__ == '__main__':
    unittest.main()
