# coding: utf-8

"""
    Ambient API

     This API provides access to Ambient services. It is designed to be used by Ambient applications and services. 

    The version of the OpenAPI document: 0.8.2
    Contact: jose@ambientlabscomputing.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ambient_backend_api_client.models.create_service_acct_request import CreateServiceAcctRequest

class TestCreateServiceAcctRequest(unittest.TestCase):
    """CreateServiceAcctRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateServiceAcctRequest:
        """Test CreateServiceAcctRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateServiceAcctRequest`
        """
        model = CreateServiceAcctRequest()
        if include_optional:
            return CreateServiceAcctRequest(
                name = 'My Service Account',
                system = True,
                description = '',
                auth_provider_uid = ''
            )
        else:
            return CreateServiceAcctRequest(
                name = 'My Service Account',
        )
        """

    def testCreateServiceAcctRequest(self):
        """Test CreateServiceAcctRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
