# coding: utf-8

"""
    Ambient API

     This API provides access to Ambient services. It is designed to be used by Ambient applications and services. 

    The version of the OpenAPI document: 0.8.2
    Contact: jose@ambientlabscomputing.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ambient_backend_api_client.models.event_label import EventLabel

class TestEventLabel(unittest.TestCase):
    """EventLabel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventLabel(self):
        """Test EventLabel"""
        # inst = EventLabel()

if __name__ == '__main__':
    unittest.main()
