# Generated by Django 3.1.5 on 2021-01-21 14:55

from django.db import migrations, models

import aleksis.core.managers


class Migration(migrations.Migration):

    dependencies = [
        ('alsijil', '0007_personal_note_lesson_documentation_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlsijilGlobalPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_data', models.JSONField(default=dict, editable=False)),
            ],
            options={
                'permissions': (('view_week', 'Can view week overview'), ('register_absence', 'Can register absence'), ('list_personal_note_filters', 'Can list all personal note filters')),
                'managed': False,
            },
            managers=[
                ('objects', aleksis.core.managers.AlekSISBaseManager()),
            ],
        ),
    ]
