# Generated by Django 3.2.3 on 2021-05-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsijil', '0012_unique_relation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessondocumentation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='personalnote',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='excusetype',
            constraint=models.UniqueConstraint(fields=('short_name',), name='unique_excuse_short_name'),
        ),
        migrations.AddConstraint(
            model_name='excusetype',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_excuse_name'),
        ),
        migrations.AddConstraint(
            model_name='extramark',
            constraint=models.UniqueConstraint(fields=('short_name',), name='unique_mark_short_name'),
        ),
        migrations.AddConstraint(
            model_name='extramark',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_mark_name'),
        ),
        migrations.AddConstraint(
            model_name='grouprole',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_role_per_site'),
        ),
        migrations.AddConstraint(
            model_name='lessondocumentation',
            constraint=models.UniqueConstraint(fields=('lesson_period', 'week', 'year', 'event', 'extra_lesson'), name='unique_documentation_per_object'),
        ),
        migrations.AddConstraint(
            model_name='personalnote',
            constraint=models.UniqueConstraint(fields=('lesson_period', 'week', 'year', 'event', 'extra_lesson'), name='unique_personal_note_per_object'),
        ),
    ]
