# Generated by Django 3.2.15 on 2022-08-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsijil', '0016_add_not_counted_excuse_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalnote',
            old_name='late',
            new_name='tardiness',
        ),
    ]
