# Generated by Django 5.0.8 on 2024-08-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alsijil', '0024_check_new_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalnote',
            name='excuse_type',
        ),
        migrations.RemoveField(
            model_name='lessondocumentation',
            name='event',
        ),
        migrations.RemoveField(
            model_name='lessondocumentation',
            name='extra_lesson',
        ),
        migrations.RemoveField(
            model_name='lessondocumentation',
            name='lesson_period',
        ),
        migrations.RemoveField(
            model_name='personalnote',
            name='event',
        ),
        migrations.RemoveField(
            model_name='personalnote',
            name='extra_lesson',
        ),
        migrations.RemoveField(
            model_name='personalnote',
            name='extra_marks',
        ),
        migrations.RemoveField(
            model_name='personalnote',
            name='groups_of_person',
        ),
        migrations.RemoveField(
            model_name='personalnote',
            name='lesson_period',
        ),
        migrations.RemoveField(
            model_name='personalnote',
            name='person',
        ),
        migrations.DeleteModel(
            name='ExcuseType',
        ),
        migrations.DeleteModel(
            name='LessonDocumentation',
        ),
        migrations.DeleteModel(
            name='PersonalNote',
        ),
    ]
