# Generated by Django 5.1.3 on 2024-11-30 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alsijil", "0025_remove_old_models"),
        ("core", "0068_calendar_event_amends_unique_constraints"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewPersonalNote",
            new_name="PersonalNote",
        ),
    ]
