"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from latitudesh_python_sdk.types import BaseModel
from latitudesh_python_sdk.utils import (
    FieldMetadata,
    HeaderMetadata,
    QueryParamMetadata,
)
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetBandwidthPlansRequestTypedDict(TypedDict):
    api_version: NotRequired[str]
    filter_id: NotRequired[str]
    r"""The plan ID to filter by"""


class GetBandwidthPlansRequest(BaseModel):
    api_version: Annotated[
        Optional[str],
        pydantic.Field(alias="API-Version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = "2023-06-01"

    filter_id: Annotated[
        Optional[str],
        pydantic.Field(alias="filter[id]"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The plan ID to filter by"""
