
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-15T05:12:41+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "2582f94808f210b96ea4cf44606a2e528129fd2f",
 "version": "0.2.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
