# This file was generated by wxPython's wscript.

VERSION_STRING    = '2025.4.15.1'
MAJOR_VERSION     = 2025
MINOR_VERSION     = 4
RELEASE_NUMBER    = 15
BUILD_TYPE        = 'development'

VERSION = (MAJOR_VERSION, MINOR_VERSION, RELEASE_NUMBER, '.1')
