# generated by datamodel-codegen:
#   filename:  properties_directory/structural/basis/atomic_coordinate.json
#   version:   0.28.5

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, Field


class AtomicCoordinate(BaseModel):
    id: Optional[float] = None
    value: Optional[Union[List[float], List[bool]]] = Field(None, title="vector schema")
