depends = ('ITKPyBase', 'ITKSmoothing', 'ITKRegistrationCommon', 'ITKMesh', 'ITKImageSources', 'ITKImageGrid', 'ITKIOMeta', 'ITKIOMeshBase', 'ITKIOImageBase', 'ITKCommon', )
templates = (  ('ParameterObject', 'elastix::ParameterObject', 'elastixParameterObject', False),
  ('ElastixRegistrationMethod', 'itk::ElastixRegistrationMethod', 'itkElastixRegistrationMethodISS2ISS2', False, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('ElastixRegistrationMethod', 'itk::ElastixRegistrationMethod', 'itkElastixRegistrationMethodISS3ISS3', False, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('ElastixRegistrationMethod', 'itk::ElastixRegistrationMethod', 'itkElastixRegistrationMethodISS4ISS4', False, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('ElastixRegistrationMethod', 'itk::ElastixRegistrationMethod', 'itkElastixRegistrationMethodIUC2IUC2', False, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ElastixRegistrationMethod', 'itk::ElastixRegistrationMethod', 'itkElastixRegistrationMethodIUC3IUC3', False, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ElastixRegistrationMethod', 'itk::ElastixRegistrationMethod', 'itkElastixRegistrationMethodIUC4IUC4', False, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >'),
  ('ElastixRegistrationMethod', 'itk::ElastixRegistrationMethod', 'itkElastixRegistrationMethodIUS2IUS2', False, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ElastixRegistrationMethod', 'itk::ElastixRegistrationMethod', 'itkElastixRegistrationMethodIUS3IUS3', False, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ElastixRegistrationMethod', 'itk::ElastixRegistrationMethod', 'itkElastixRegistrationMethodIUS4IUS4', False, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >'),
  ('ElastixRegistrationMethod', 'itk::ElastixRegistrationMethod', 'itkElastixRegistrationMethodIF2IF2', False, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('ElastixRegistrationMethod', 'itk::ElastixRegistrationMethod', 'itkElastixRegistrationMethodIF3IF3', False, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('ElastixRegistrationMethod', 'itk::ElastixRegistrationMethod', 'itkElastixRegistrationMethodIF4IF4', False, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('ElastixRegistrationMethod', 'itk::ElastixRegistrationMethod', 'itkElastixRegistrationMethodID2ID2', False, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('ElastixRegistrationMethod', 'itk::ElastixRegistrationMethod', 'itkElastixRegistrationMethodID3ID3', False, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('ElastixRegistrationMethod', 'itk::ElastixRegistrationMethod', 'itkElastixRegistrationMethodID4ID4', False, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('TransformixFilter', 'itk::TransformixFilter', 'itkTransformixFilterISS2', False, 'itk::Image< signed short,2 >'),
  ('TransformixFilter', 'itk::TransformixFilter', 'itkTransformixFilterISS3', False, 'itk::Image< signed short,3 >'),
  ('TransformixFilter', 'itk::TransformixFilter', 'itkTransformixFilterISS4', False, 'itk::Image< signed short,4 >'),
  ('TransformixFilter', 'itk::TransformixFilter', 'itkTransformixFilterIUC2', False, 'itk::Image< unsigned char,2 >'),
  ('TransformixFilter', 'itk::TransformixFilter', 'itkTransformixFilterIUC3', False, 'itk::Image< unsigned char,3 >'),
  ('TransformixFilter', 'itk::TransformixFilter', 'itkTransformixFilterIUC4', False, 'itk::Image< unsigned char,4 >'),
  ('TransformixFilter', 'itk::TransformixFilter', 'itkTransformixFilterIUS2', False, 'itk::Image< unsigned short,2 >'),
  ('TransformixFilter', 'itk::TransformixFilter', 'itkTransformixFilterIUS3', False, 'itk::Image< unsigned short,3 >'),
  ('TransformixFilter', 'itk::TransformixFilter', 'itkTransformixFilterIUS4', False, 'itk::Image< unsigned short,4 >'),
  ('TransformixFilter', 'itk::TransformixFilter', 'itkTransformixFilterIF2', False, 'itk::Image< float,2 >'),
  ('TransformixFilter', 'itk::TransformixFilter', 'itkTransformixFilterIF3', False, 'itk::Image< float,3 >'),
  ('TransformixFilter', 'itk::TransformixFilter', 'itkTransformixFilterIF4', False, 'itk::Image< float,4 >'),
  ('TransformixFilter', 'itk::TransformixFilter', 'itkTransformixFilterID2', False, 'itk::Image< double,2 >'),
  ('TransformixFilter', 'itk::TransformixFilter', 'itkTransformixFilterID3', False, 'itk::Image< double,3 >'),
  ('TransformixFilter', 'itk::TransformixFilter', 'itkTransformixFilterID4', False, 'itk::Image< double,4 >'),
)
factories = ()
