from typing import Optional, Union

class z3engine:
    def __init__(self, serial: Optional[str] = None) -> None: ...

    # Initialization
    def init() -> None: ...
    def terminate() -> None: ...    
    # Device Information
    def get_device_info(selector: str) -> dict: ...    
    # Device Control
    def set_gear(gear: Union[str, int], dot: bool = ...) -> None: ...
    def set_left_panel(text: str) -> None: ...
    def set_right_panel(text: str) -> None: ...
    def set_rpm_led(value: int, state: int) -> None: ...
    def set_warning_led(value: int, state: int) -> None: ...
    def set_external_led(value: int, state: int) -> None: ...
    def set_brightness(level: int) -> None: ...
    def show_me() -> None: ...    
    # Input Handling
    def start_input_listener() -> None: ...
    def stop_input_listener() -> None: ...
    def get_input_data() -> dict: ...