
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-16T14:21:03+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "171a041d713e8c406380ca62c6d8774a66bec3c7",
 "version": "0.1.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
