"""
noiseModel submodule
"""
from __future__ import annotations
import numpy
import typing
from . import mEstimator
__all__ = ['Base', 'Constrained', 'Diagonal', 'Gaussian', 'Isotropic', 'Robust', 'Unit', 'mEstimator']
class Base:
    def __repr__(self, s: str = '') -> str:
        ...
    def print(self, s: str = '') -> None:
        ...
class Constrained(Diagonal):
    @staticmethod
    @typing.overload
    def All(dim: int) -> Constrained:
        ...
    @staticmethod
    @typing.overload
    def All(dim: int, mu: float) -> Constrained:
        ...
    @staticmethod
    @typing.overload
    def MixedPrecisions(mu: numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]], precisions: numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]]) -> Constrained:
        ...
    @staticmethod
    @typing.overload
    def MixedPrecisions(precisions: numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]]) -> Constrained:
        ...
    @staticmethod
    @typing.overload
    def MixedSigmas(mu: numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]], sigmas: numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]]) -> Constrained:
        ...
    @staticmethod
    @typing.overload
    def MixedSigmas(m: float, sigmas: numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]]) -> Constrained:
        ...
    @staticmethod
    @typing.overload
    def MixedVariances(mu: numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]], variances: numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]]) -> Constrained:
        ...
    @staticmethod
    @typing.overload
    def MixedVariances(variances: numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]]) -> Constrained:
        ...
    def __getstate__(self) -> tuple:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def serialize(self) -> str:
        ...
    def unit(self) -> Constrained:
        ...
class Diagonal(Gaussian):
    @staticmethod
    def Precisions(precisions: numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]], smart: bool = True) -> Diagonal:
        ...
    @staticmethod
    def Sigmas(sigmas: numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]], smart: bool = True) -> Diagonal:
        ...
    @staticmethod
    def Variances(variances: numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]], smart: bool = True) -> Diagonal:
        ...
    def R(self) -> numpy.ndarray[tuple[M, N], numpy.dtype[numpy.float64]]:
        ...
    def __getstate__(self) -> tuple:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def invsigmas(self) -> numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]]:
        ...
    def precisions(self) -> numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]]:
        ...
    def serialize(self) -> str:
        ...
    def sigmas(self) -> numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]]:
        ...
class Gaussian(Base):
    @staticmethod
    def Covariance(R: numpy.ndarray[tuple[M, N], numpy.dtype[numpy.float64]], smart: bool = True) -> Gaussian:
        ...
    @staticmethod
    def Information(R: numpy.ndarray[tuple[M, N], numpy.dtype[numpy.float64]], smart: bool = True) -> Gaussian:
        ...
    @staticmethod
    def SqrtInformation(R: numpy.ndarray[tuple[M, N], numpy.dtype[numpy.float64]], smart: bool = True) -> Gaussian:
        ...
    def R(self) -> numpy.ndarray[tuple[M, N], numpy.dtype[numpy.float64]]:
        ...
    def Whiten(self, H: numpy.ndarray[tuple[M, N], numpy.dtype[numpy.float64]]) -> numpy.ndarray[tuple[M, N], numpy.dtype[numpy.float64]]:
        ...
    def __getstate__(self) -> tuple:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def covariance(self) -> numpy.ndarray[tuple[M, N], numpy.dtype[numpy.float64]]:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def equals(self, expected: Base, tol: float) -> bool:
        ...
    def information(self) -> numpy.ndarray[tuple[M, N], numpy.dtype[numpy.float64]]:
        ...
    def negLogConstant(self) -> float:
        ...
    def serialize(self) -> str:
        ...
    def unwhiten(self, v: numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]]) -> numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]]:
        ...
    def whiten(self, v: numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]]) -> numpy.ndarray[tuple[M, typing.Literal[1]], numpy.dtype[numpy.float64]]:
        ...
class Isotropic(Diagonal):
    @staticmethod
    def Precision(dim: int, precision: float, smart: bool = True) -> Isotropic:
        ...
    @staticmethod
    def Sigma(dim: int, sigma: float, smart: bool = True) -> Isotropic:
        ...
    @staticmethod
    def Variance(dim: int, varianace: float, smart: bool = True) -> Isotropic:
        ...
    def __getstate__(self) -> tuple:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def serialize(self) -> str:
        ...
    def sigma(self) -> float:
        ...
class Robust(Base):
    @staticmethod
    def Create(robust: mEstimator.Base, noise: Base) -> Robust:
        ...
    def __getstate__(self) -> tuple:
        ...
    def __init__(self, robust: mEstimator.Base, noise: Base) -> None:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def serialize(self) -> str:
        ...
class Unit(Isotropic):
    @staticmethod
    def Create(dim: int) -> Unit:
        ...
    def __getstate__(self) -> tuple:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def serialize(self) -> str:
        ...
