
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-15T12:52:42-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9e7964e7ec878ba238b4b334e8ac0a9792c1817c",
 "version": "2.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
