
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-15T10:16:40+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bebc34ab0c15d175dc7cf5232b07ed8acb3cf420",
 "version": "0.1.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
